### ISSUE TITLE
users.db commited to git

### ISSUE THREAD

**Issue by szabgab** [EzekTec-Inc/hyper-microservice#2]
There is a file called `users.db` with some data in it committed to git. I'd probably remove that and put its name in `.gitignore`

**Comment by EzekTec-Inc** [comment]
You're right, however I included it here as its and Sqlite database that just contains faux content for the user to be able to download and user for their testing purposes of the microservice without having to setup anything else.

I've updated the README.md file to include a note on this.

Thanks

**Comment by EzekTec-Inc** [comment]
README.md file updated with changes and instructions on how to use users.db sqlite file.
