### ISSUE TITLE
Exclude .env from git

### ISSUE THREAD

**Issue by szabgab** [EzekTec-Inc/hyper-microservice#3]
Each installation needs to have its own `.env` file so having it in git means I'll have a changed version in my clone.

It would be better to exclude it from git and have a skeleton in the repository, e.g. `.env.skeleton` then the instructions in README would be to copy `.env.skeleton` to `.env` and update the latter.

**Comment by EzekTec-Inc** [comment]
Thanks for the observation here, however I included it intentionally as it does not contains an api-keys or credentials required to run the microservice. I intend the project to be downloaded in one go and just run without the user trying to configure anything to see how the service works.
