### ISSUE TITLE
Setting content-type to json

### ISSUE THREAD

**Issue by szabgab** [EzekTec-Inc/hyper-microservice#5]
```
curl -i -X GET http://0.0.0.0:3000/products
```
returns

```
HTTP/1.1 200 OK
content-length: 589
date: Wed, 07 Aug 2024 06:59:30 GMT

[{"product_id":1,"product_name":"welcome","created_on":"2024-07-27","updated_on":"2024-07-27","img_directory":"/path/to/img/","out_directory":"/path/to/out/","status":"Done","settings_id":1},{"product_id":2,"product_name":"EV Car","created_on":"2024-07-26","updated_on":"2024-07-28","img_directory":"/path/to/img/","out_directory":"/path/to/out/","status":"InProgress","settings_id":1},{"product_id":3,"product_name":"Floor divider","created_on":"2024-07-31","updated_on":"2024-08-01","img_directory":"/path/to/img/","out_directory":"/path/to/out/","status":"Not Started","settings_id":1}]
```

so it seems the content-type is not set.

IMHO it should be `application/json`

**Comment by EzekTec-Inc** [comment]
For now, I am returning json payload but do hope to implement JSON-RPC principles on the API service to allow the user decide to call multiple services and return the data in various formats (cbor, json, csv & plain-text).

I have updated the instructions to include passing in -H "Content-Type: application/json" in the header of the curl call, however the server does not do anything with it as I'm not yet checking the header tags for data format information.

I'll appreciate your help and guide on how to approach what I have described here. 

Thanks
