### ISSUE TITLE
microservices.toml vs microserves.toml

### ISSUE THREAD

**Issue by szabgab** [EzekTec-Inc/hyper-microservice#6]
The code tries to open `microserves.toml` which does not exist and then complains about missing file. The comment in the code mentions `microservices.toml` that exists. (but probably should not be committed to git either)

**Comment by EzekTec-Inc** [comment]
Thank you for catching this, I've added it to the .gitignore list. It was originally meant to be an alternative method of setting the microservice server address and port, which I'm yet to implement in the v0.2.0 of this project.
